backend:
  name: git-gateway
  branch: main 

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts & Certificates"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      # This line adds the dropdown menu for sorting
      - {label: "Category", name: "category", widget: "select", options: ["Project", "Certificate"], default: "Project"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # The body uses Markdown so you can upload pictures, videos, and write long text
      - {label: "Content (Images, Text, Links)", name: "body", widget: "markdown"}
