backend:
  name: git-gateway
  repo: Erfansalehii/portfolio
  branch: main 
  base_url: https://decap-cms-oauth.vercel.app # This line handles the login

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
